export const ENV_VARS = {
  PORT: "PORT",
  MONGO_DB_USER: "MONGO_DB_USER",
  MONGO_DB_PASSWORD: "MONGO_DB_PASSWORD",
  MONGO_DB_HOST: "MONGO_DB_HOST",
  MONGO_DB_DB: "MONGO_DB_DB",
  JWT_SECRET: "JWT_SECRET",
  APP_DOMAIN: "APP_DOMAIN",
};

export const SMTP = {
  SMTP_HOST: "SMTP_HOST",
  SMTP_PORT: "SMTP_PORT",
  SMTP_USER: "SMTP_USER",
  SMTP_PASSWORD: "SMTP_PASSWORD",
  SMTP_FROM: "SMTP_FROM",
};

export const CLOUDINARY = {
  CLOUD_NAME: "CLOUD_NAME",
  API_KEY: "API_KEY",
  API_SECRET: "API_SECRET",
  ENABLE_CLOUDINARY: "ENABLE_CLOUDINARY",
};
